---
# tasks file for kvm (Ubuntu specific)

- name: Install KVM packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ kvm_packages }}"
  tags:
    - kvm
