---
# tasks file for kvm (Ubuntu specific)

- name: Install KVM packages
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: kvm_packages
  tags: 
    - kvm
    - install
